import React, { useState } from "react";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import "../../index.css";

function LearnMore() {
  const [isLoaded, setIsLoaded] = useState(false);
  return (
    <div>
      <Header />
      <br />
      <div className=" p-5">
        <div className="text-3xl text-center font-bold ">
          What is Electroencephalogram ?
        </div>
        <br />
        <div className="text-xl  ">
          EEG (Electroencephalogram) is a test that measures the electrical
          activity in the brain. It uses small sensors placed on the scalp to
          detect brainwaves, which are the electrical impulses generated by
          neurons communicating with each other.
        </div>
        <br />
        <div className="flex flex-row gap-10 ">
          <div>
            <img
              src="LearnMore/img1.png"
              className="w-50 h-96 animate-slide-in-left"
              style={{ animation: "slide-in-left 1s ease-out forwards" }}
              onLoad={() => setIsLoaded(true)}
            />
          </div>
          <div>
            <img src="LearnMore/img2.png" className="w-50 h-96 " />
          </div>
          <div>
            <img
              src="LearnMore/img3.png"
              className="w-50 h-96 animate-slide-in-right"
              style={{ animation: "slide-in-right 1s ease-out forwards" }}
              onLoad={() => setIsLoaded(true)}
            />
          </div>
        </div>
      </div>
      <div className="max-w-3xl mx-auto p-6 bg-[#A3DAC2] rounded-lg shadow-md" style={{ animation: "slide-in-right 1s ease-out forwards" }}
              onLoad={() => setIsLoaded(true)}>
        <h2 className="text-2xl font-semibold text-[#252b61] mb-4">
          Importance of EEG
        </h2>
        <div className="space-y-4">
          <div>
            <h3 className="text-xl font-medium text-[#252b61] ">
              Diagnosing Brain Conditions
            </h3>
            <p className="text-[#252b61]">
              EEG is commonly used to detect and monitor brain disorders like
              epilepsy, sleep problems, and head injuries.
            </p>
          </div>
          <div>
            <h3 className="text-xl font-medium text-[#252b61] ">
              Real-Time Brain Monitoring
            </h3>
            <p className="text-[#252b61]">
              It provides immediate information on brain function, helping
              doctors understand abnormal brain activity and monitor patients
              during surgery or in intensive care.
            </p>
          </div>
          <div>
            <h3 className="text-xl font-medium text-[#252b61] ">
              Understanding Brain Function
            </h3>
            <p className="text-[#252b61]">
              EEG allows scientists and researchers to study how the brain
              works, including how it responds to stimuli and how different
              areas of the brain are involved in thought and action.
            </p>
          </div>
          <div>
            <h3 className="text-xl font-medium text-[#252b61] ">
              Improving Treatments
            </h3>
            <p className="text-[#252b61]">
              By tracking brainwave patterns, EEG helps evaluate the
              effectiveness of treatments for neurological disorders and adjust
              them as needed.
            </p>
          </div>
          <div>
            <p className="text-[#252b61]">
              In short, EEG is a valuable tool for both medical diagnosis and
              research, offering insights into the brain’s activity and health.
            </p>
          </div>
        </div>
      </div>
      <br/>

      <Footer />
    </div>
  );
}
export default LearnMore;
